global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'prometheus-monitor'

scrape_configs:

  # monitor prometheus itself
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'web-servers'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.7.81:8000','192.168.7.81:8001']
        labels:
          group: 'production'
      - targets: ['192.168.7.81:8002']
        labels:
          group: 'canary'

  # get other scrape targets from consul
  # - job_name: consul
  #   scrape_interval: 5s
  #   consul_sd_configs:
  #     - server: 'localhost:8500'